### ISSUE TITLE
Crash as I continue the game

### ISSUE THREAD

**Issue by comicsteel** [0x5abe/PlatformerSaves#6]
It crashes everytime I tried to continue the game

**Comment by 0x5abe** [comment]
Hey! 

Can you please attach a screenshot of the crashlog or the crashlog file? (it should be in your gd folder then geode/crashlogs)

Also if you can send the **save file** for the level that would be helpful. It's stored in %localappdata%\GeometryDash\geode\mods\sabe.platformersaves\saves\ and then depending on if it's a base game level it's in the local folder, if it's an editor level it's in editor and if it's an online level it's in online. If it's online the **level id** is the name of the folder and inside there's a file called slot0, you should send that.

**Comment by comicsteel** [comment]
ss: ![image](https://github.com/0x5abe/PlatformerSaves/assets/173171414/26f3eb63-3372-4f06-bf90-9bc7bfc8c949)
slot0: https://cdn.discordapp.com/attachments/891517866044715048/1257195415288418314/slot0.psf?ex=668385f8&is=66823478&hm=911e79632c519f617c8fe8eb0530e1c8381f35617756602a2ab16d0a88a8e41f&

**Comment by comicsteel** [comment]
This happens when I relaunch GD and continue the level "Pixelpath II" btw

**Comment by 0x5abe** [comment]
It's most likely some type of object that the level uses that I wasn't able to test enough since it's probably not used a lot in levels. I'll look at it in detail, but there's probably a fix. It may take a bit to figure out tho so for now until it's fixed I would recommend just playing it from the start, sorry about that.

**Comment by 0x5abe** [comment]
Supposedly fixed in the latest PersistenceAPI release pending approval. Once it's able for download you should update and the crash will no longer happen, but you will have to start a new game and overwrite the existing save file for it to work properly.

I'll wait a bit before closing the issue, until the new version of PersistenceAPI is in the index and you can confirm it works correctly.

**Comment by comicsteel** [comment]
alr

**Comment by 0x5abe** [comment]
I'll close this for now, if there's any other problem let me know
